import { CatalogModel } from './modelCatalog';

export const CATALOG_SEED: CatalogModel[] = [
  {
    id: 'anthropic/claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    context_length: 200000,
    pricing: { prompt: '0.000003', completion: '0.000015' },
    supports_tools: true,
    supports_structured_outputs: true,
    tier: 'MID',
  },
  {
    id: 'anthropic/claude-3-opus',
    name: 'Claude 3 Opus',
    provider: 'anthropic',
    context_length: 200000,
    pricing: { prompt: '0.000015', completion: '0.000075' },
    supports_tools: true,
    supports_structured_outputs: true,
    tier: 'PREMIUM',
  },
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    context_length: 128000,
    pricing: { prompt: '0.0000025', completion: '0.00001' },
    supports_tools: true,
    supports_structured_outputs: true,
    tier: 'PREMIUM',
  },
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    context_length: 128000,
    pricing: { prompt: '0.00000015', completion: '0.0000006' },
    supports_tools: true,
    supports_structured_outputs: true,
    tier: 'CHEAP',
  },
  {
    id: 'google/gemini-pro-1.5',
    name: 'Gemini Pro 1.5',
    provider: 'google',
    context_length: 1000000,
    pricing: { prompt: '0.0000025', completion: '0.0000075' },
    supports_tools: true,
    supports_structured_outputs: true,
    tier: 'MID',
  },
  {
    id: 'google/gemini-flash-1.5',
    name: 'Gemini Flash 1.5',
    provider: 'google',
    context_length: 1000000,
    pricing: { prompt: '0.00000035', completion: '0.00000105' },
    supports_tools: true,
    supports_structured_outputs: true,
    tier: 'CHEAP',
  },
  {
    id: 'deepseek/deepseek-chat',
    name: 'DeepSeek V3',
    provider: 'deepseek',
    context_length: 64000,
    pricing: { prompt: '0.00000014', completion: '0.00000028' },
    supports_tools: true,
    supports_structured_outputs: true,
    tier: 'CHEAP',
  },
  {
    id: 'x-ai/grok-2',
    name: 'Grok 2',
    provider: 'x-ai',
    context_length: 131072,
    pricing: { prompt: '0.000002', completion: '0.00001' },
    supports_tools: true,
    supports_structured_outputs: true,
    tier: 'MID',
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B',
    provider: 'meta-llama',
    context_length: 128000,
    pricing: { prompt: '0.0000004', completion: '0.0000004' },
    supports_tools: true,
    supports_structured_outputs: true,
    tier: 'CHEAP',
  },
];
